directories:
  output: release
  buildResources: build
appId: com.nuevasiembra.pos
productName: Nueva Siembra POS
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
asarUnpack:
  - '**/*.node'
icon: public/icon.ico
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/icon.ico
  signAndEditExecutable: false
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Nueva Siembra POS
  installerIcon: public/icon.ico
  uninstallerIcon: public/icon.ico
  installerHeaderIcon: public/icon.ico
electronVersion: 28.3.3
